CREATE TABLE assignees (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL COLLATE NOCASE UNIQUE,
  color TEXT NOT NULL CHECK (length(color) = 7 AND substr(color, 1, 1) = '#'),
  position INTEGER NOT NULL UNIQUE,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
);

INSERT INTO assignees VALUES ('assignee-iv', 'ІВ', '#00B050', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO assignees VALUES ('assignee-vtk', 'Втк', '#FF9999', 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO assignees VALUES ('assignee-yev', 'Єв', '#FF99FF', 3, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO assignees VALUES ('assignee-ol', 'Ол', '#FFCC66', 4, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO assignees VALUES ('assignee-my', 'Ми', '#66FFFF', 5, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO assignees VALUES ('assignee-ro', 'Ро', '#CCFF66', 6, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO assignees VALUES ('assignee-va', 'Ва', '#00B0F0', 7, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO assignees VALUES ('assignee-ih', 'Іг', '#FFFF99', 8, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO assignees VALUES ('assignee-na', 'На', '#538DD5', 9, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO assignees VALUES ('assignee-vta', 'Вта', '#BFBFBF', 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO assignees VALUES ('assignee-tr', 'Тр', '#92D050', 11, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO assignees VALUES ('assignee-vv', 'Вв', '#948A54', 12, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO assignees VALUES ('assignee-ai', 'Ай', '#DA9694', 13, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO assignees VALUES ('assignee-yul', 'Юл', '#FABF8F', 14, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO assignees VALUES ('assignee-oo', 'Оо', '#B1A0C7', 15, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO assignees VALUES ('assignee-tn', 'Тн', '#FFC000', 16, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO assignees VALUES ('assignee-sv', 'Св', '#76933C', 17, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
